name: flutter_getx_base
description: Flutter GetX Base App
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'
#environment:
#  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  logger: ^2.4.0
  image_picker: ^1.1.2
  photo_manager: ^3.5.2

  # for logging
  loggy: ^2.0.1+1
  test: ^1.25.7
  csv: ^6.0.0
  flutter_markdown: ^0.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700